### ISSUE TITLE
Proposal to contribute a blog to the misp-project.org website 

### ISSUE THREAD

**Issue by adulau** [andreatripoli/mispotx#1]
Congrats for the mispotx project is really nice and will help a lot of MISP users using OTX too. I was wondering if you would be interested to do a blog post on the misp-project.org website. Don’t hesitate to make a pull-request on https://github.com/MISP/misp-website if you are interested. Thanks again for your work.

**Comment by andreatripoli** [comment]
Dear Alexandre,
I'm so sorry if I reply now, but as I didn't receive the notification, I missed your message.

I would be very happy to participate and write a misp-project.org post to share the contribution.

I inform you that a new version of mispotx will be released (with the latest version of PyMISP) and a feature correction.

I can tell you that other "modules" will be released in the next few weeks.


I remain at your disposal for any information. Thank you for your message and for the contribution you make

Greetings,
A.T.
